global:
  resolve_timeout: 5m
  smtp_smarthost: "smtp.example.com:587"
  smtp_from: "alertmanager@example.com"
  smtp_auth_username: "alertmanager"
  smtp_auth_password: "password"
  smtp_require_tls: true
  slack_api_url: "https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK"

templates:
  - "/etc/alertmanager/templates/*.tmpl"

route:
  group_by: ["alertname", "instance", "severity"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: "email-notifications"
  routes:
    - match:
        severity: critical
      receiver: "email-notifications"
      continue: true
    - match:
        severity: warning
      receiver: "slack-notifications"
      continue: true

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "instance"]

receivers:
  - name: "email-notifications"
    email_configs:
      - to: "alerts@example.com"
        send_resolved: true
        html: '{{ template "email.default.html" . }}'
        headers:
          subject: '{{ template "email.default.subject" . }}'

  - name: "slack-notifications"
    slack_configs:
      - channel: "#monitoring-alerts"
        send_resolved: true
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}{{ if .Annotations.description }}
            *Description:* {{ .Annotations.description }}{{ end }}
            *Severity:* {{ .Labels.severity }}
            *Instance:* {{ .Labels.instance }}
            *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
