server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Application logs
  # - job_name: application
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: application
  #         host: app.cw.internal
  #         __path__: /var/log/app/*.log

  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          host: 'monitor01.cw.internal'
          __path__: /var/log/*log

  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
      - source_labels:
          ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
      - target_label: 'host'
        replacement: 'monitor01.cw.internal'
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            log: log
            attrs: attrs
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: log

  # Fallback for containers without our custom labels
  - job_name: docker_fallback
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          host: 'monitor01.cw.internal'
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag
            source: source
      - labels:
          stream:
          tag:
      - regex:
          expression: '(?P<container_id>(?:[0-9a-f]{64}|[0-9a-f]{12}))'
          source: filename
      - docker:
          container_name_label: container_name
          stream_label: stream
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: log
      - labeldrop:
          - attrs
          - tag
